dist: bin

builds:
- dir: cmd
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
  goarm:
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
  gcflags:
    - all=-trimpath={{.Env.GOPATH}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - completions/autocomplete.sh

source:
  enabled: true

release:
  prerelease: auto

checksum:
  name_template: checksums.txt

changelog:
  skip: true

brews:
  - tap:
      owner: trntv
      name: homebrew-sshed
    commit_author:
      name: Yevhen Terentiev
      email: yevhen.terentiev@gmail.com
    homepage: https://github.com/trntv/sshed
    install: |
        bin.install "sshed"
        bash_completion.install "completions/autocomplete.sh"
      
dockers:
  - image_templates:
      - "docker.io/trntv/sshed:latest"
      - "docker.io/trntv/sshed:{{ .Tag }}"
    skip_push: auto

scoop:
  bucket:
    owner: trntv
    name: scoop-sshed
  commit_author:
    name: Yevhen Terentiev
    email: yevhen.terentiev@gmail.com
  homepage: https://github.com/trntv/sshed

nfpms:
  -
    homepage: https://github.com/trntv/sshed
    maintainer: Yevhen Terentiev <yevhen.terentiev@gmail.com>
    formats:
      - deb
      - rpm
